// Package glyph provides the overlay's monochrome icons (class badges and tab
// icons) as alpha masks scaled to any pixel size. The artwork is original and
// generated by assets/make_glyphs.py.
package glyph

import (
	"embed"
	"fmt"
	"image"
	"image/png"
	"sync"
)

//go:embed png/*.png
var files embed.FS

type key struct {
	name string
	size int
}

var (
	mu     sync.Mutex
	master = map[string]*image.Gray{}
	cache  = map[key][]uint8{}
)

func load(name string) (*image.Gray, error) {
	if g, ok := master[name]; ok {
		return g, nil
	}
	f, err := files.Open("png/" + name + ".png")
	if err != nil {
		return nil, err
	}
	defer f.Close()
	img, err := png.Decode(f)
	if err != nil {
		return nil, err
	}
	b := img.Bounds()
	g := image.NewGray(b)
	for y := b.Min.Y; y < b.Max.Y; y++ {
		for x := b.Min.X; x < b.Max.X; x++ {
			r, gg, bb, a := img.At(x, y).RGBA()
			v := (r + gg + bb) / 3
			if _, isGray := img.(*image.Gray); !isGray {
				v = v * a / 0xFFFF
			}
			g.Pix[(y-b.Min.Y)*g.Stride+(x-b.Min.X)] = uint8(v >> 8)
		}
	}
	master[name] = g
	return g, nil
}

// Mask returns a size×size coverage mask (0..255) for the named glyph,
// e.g. "class_11" or "tab_dps". Returns nil if the glyph doesn't exist.
func Mask(name string, size int) []uint8 {
	if size <= 0 {
		return nil
	}
	mu.Lock()
	defer mu.Unlock()
	k := key{name, size}
	if m, ok := cache[k]; ok {
		return m
	}
	src, err := load(name)
	if err != nil {
		cache[k] = nil
		return nil
	}
	m := scale(src, size)
	cache[k] = m
	return m
}

// scale does an area-average (box) resample, good for downscaling icons.
func scale(src *image.Gray, n int) []uint8 {
	sw, sh := src.Bounds().Dx(), src.Bounds().Dy()
	out := make([]uint8, n*n)
	fx, fy := float64(sw)/float64(n), float64(sh)/float64(n)
	for oy := 0; oy < n; oy++ {
		y0, y1 := float64(oy)*fy, float64(oy+1)*fy
		for ox := 0; ox < n; ox++ {
			x0, x1 := float64(ox)*fx, float64(ox+1)*fx
			var sum, area float64
			for sy := int(y0); sy < sh && float64(sy) < y1; sy++ {
				wy := min(y1, float64(sy+1)) - max(y0, float64(sy))
				for sx := int(x0); sx < sw && float64(sx) < x1; sx++ {
					wx := min(x1, float64(sx+1)) - max(x0, float64(sx))
					w := wx * wy
					sum += float64(src.Pix[sy*src.Stride+sx]) * w
					area += w
				}
			}
			if area > 0 {
				out[oy*n+ox] = uint8(sum/area + 0.5)
			}
		}
	}
	return out
}

// ClassGlyph returns the glyph name for a class id (spirit uses elementalist).
func ClassGlyph(classID int) string {
	if classID >= 10 && classID <= 19 {
		return fmt.Sprintf("class_%d", classID)
	}
	return ""
}
